# actions/checkout@v2 does not support sparse checkout as of Dec 2021

name: "git sparse checkout"
description: "git sparse checkout"
author: "Travis"

inputs:
  token:
    description: "A Github Private Access Token"
    default: ${{ github.token }}
    required: false

  paths:
    description: "Folders and files to checkout from the repo"
    required: true

runs:
  using: "composite"
  steps:
    - id: main
      shell: bash
      run: |
        REPO="https://${GITHUB_ACTOR}:${{ inputs.token }}@github.com/${GITHUB_REPOSITORY}.git"
        git clone --filter=blob:none --no-checkout --depth 1 --single-branch --branch ${GITHUB_REF_NAME} --sparse $REPO ${GITHUB_WORKSPACE}
        git sparse-checkout init --cone
        git sparse-checkout add ${{ inputs.paths }}
        git checkout
