name: "Install Kubectl Tool and Set Up Context"
author: "travis"
description: "Download the kubectl command line tool with the specified version or latest version by default and set up the kube configuration"
inputs:
  version:
    description: "Kubectl Version"
    required: false
    default: "latest"
  kube_config:
    description: "Kubectl configuration data"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - id: main
      shell: bash
      run: ${{ github.action_path }}/scripts/main.sh
      env:
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_KUBE_CONFIG: ${{ inputs.kube_config }}
